### ISSUE TITLE
Moving LibQGit2 under libgit2 "organization" in GitHub?

### ISSUE THREAD

**Issue by akikoskinen** [libgit2/discussions#10]
There is this C++/Qt language binding library for libgit2, that is also mentioned on the libgit2 website: LibQGit2. There hasn't been much interest in that project and it has stagnated for a few years now. Currently it uses libgit2 API from version 0.22. But: it is about to be resurrected and patches exist (not yet pushed) already that adapt to libgit2 API version 0.27.

I'm writing this issue because LibQGit2 is currently hosted in the [KDE infrastructure](https://phabricator.kde.org/source/libqgit2/). During the past three years I and one another guy (with whom I was working) are the only contributors to the LibQGit2 project. I can say pretty strongly that the project was bequeathed to me.

I don't see any benefit in having LibQGit2 in the KDE infrastructure. I would propose that the repository shall be moved under the libgit2 organization in GitHub – just like pretty much all the other language binding libraries are. Could this be achieved? What would it mean in practice, politically and otherwise? Would it make libgit2 somehow (differently than currently) endorse LibQGit2 or something?

**Comment by ethomson** [comment]
👍  Thanks for working on this @akikoskinen, excited to see what's coming next for LibQGit2.

**Comment by pks-t** [comment]
I'm marking this discussion as closed, as it seems like you to guys figured out the best way to handle this. Feel free to reopen it, though, in case you want to further the discussion.
